export TERM=xterm-256color

alias v='nvim'
alias vim='nvim'

Y() {
	youtube-dl \
		--audio-quality=128k \
		-f worst \
		-o "$HOME/data/media/%(channel)s-%(release_date)s-%(id)s.%(ext)s" \
		-x "$@"
}
. $PREFIX/share/bash-completion/bash_completion
